In [1]:
#Working on list
#it cant perform operations on list
a=[1,2,3]
b=[4,5,6]
print(a*b)

TypeError: can't multiply sequence by non-int of type 'list'

In [2]:
# to do prev calculation use numpy 
import numpy as np
np_a=np.array(a)
np_b=np.array(b)
print(np_a*np_b)

[ 4 10 18]


In [3]:
a_zero=np.zeros((2,3))
print(type(a_zero))

<class 'numpy.ndarray'>


In [4]:
a_one=np.ones((2,3))
print(a_one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
a_arange=np.arange(8)
print(a_arange)

[0 1 2 3 4 5 6 7]


In [8]:
a_arange.reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
#lin space
n_lin=np.linspace(1,20,5)
print(n_lin)

[ 1.    5.75 10.5  15.25 20.  ]


In [15]:
#1 D array
one_d_array=np.arange(15)
print(one_d_array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [20]:
#convert 1 D array into 2 D array
two_d_array=one_d_array.reshape(3,5)
print(two_d_array)
print(type(two_d_array))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


In [22]:
#3 D Array
three_d_array=np.arange(27).reshape(3,3,3)
print(three_d_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [25]:
#attributes of array
three_d_array.ndim

3

In [26]:
three_d_array.shape

(3, 3, 3)

In [27]:
three_d_array.size

27

In [28]:
three_d_array.dtype

dtype('int32')